spring:
  application:
    name: user-service
  config:
    import:
      - application-db.yml
      - application-jpa.yml
      - application-cloud.yml
      - classpath:/bootstrap.yml # *classpath:

server:
  port: 0