spring:
  application:
    name: user-service
  config:
    import:
      - application-db.yml
      - application-jpa.yml
      - application-cloud.yml
      - application-security.yml

server:
  port: 0

greeting:
  message: Welcome to the simple e-commerce