spring.config.activate.on-profile: local

spring:
  jpa:
    database: h2
    show-sql: false
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 500
    defer-datasource-initialization: true