server:
  port: 8000
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://127.0.0.1:0/
          predicates:
            - Path=/user-service/**